"""create core schema

Revision ID: 4c047544de4d
Revises: 
Create Date: 2026-09-26 16:47:22.413204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c047544de4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('key', name=op.f('uq_categories_key'))
    )
    op.create_table('teachers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teachers')),
    sa.UniqueConstraint('email', name=op.f('uq_teachers_email'))
    )
    op.create_table('vocabulary_senses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sense_key', sa.String(length=400), nullable=False),
    sa.Column('headword', sa.String(length=200), nullable=False),
    sa.Column('headword_normalized', sa.String(length=200), nullable=False),
    sa.Column('part_of_speech', sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'PHRASE', 'OTHER', name='part_of_speech', native_enum=False), nullable=True),
    sa.Column('cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level', native_enum=False), nullable=True),
    sa.Column('definition_preview', sa.Text(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('priority_level', sa.String(length=20), nullable=True),
    sa.Column('priority_version', sa.String(length=20), nullable=True),
    sa.Column('processing_version', sa.String(length=20), server_default='v0-bootstrap', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_senses')),
    sa.UniqueConstraint('sense_key', name=op.f('uq_vocabulary_senses_sense_key'))
    )
    op.create_index('ix_senses_cefr', 'vocabulary_senses', ['cefr_level'], unique=False)
    op.create_index('ix_senses_headword_norm', 'vocabulary_senses', ['headword_normalized'], unique=False)
    op.create_index('ix_senses_pos', 'vocabulary_senses', ['part_of_speech'], unique=False)
    op.create_index('ix_senses_priority', 'vocabulary_senses', ['priority_score'], unique=False)
    op.create_table('vocabulary_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('import_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_sources')),
    sa.UniqueConstraint('key', name=op.f('uq_vocabulary_sources_key'))
    )
    op.create_table('wordnet_synsets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('synset_id', sa.String(length=30), nullable=False),
    sa.Column('part_of_speech', sa.String(length=3), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('ili', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wordnet_synsets')),
    sa.UniqueConstraint('synset_id', name=op.f('uq_wordnet_synsets_synset_id'))
    )
    op.create_table('cefr_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_cefr_evidence_sense_id_vocabulary_senses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['vocabulary_sources.id'], name=op.f('fk_cefr_evidence_source_id_vocabulary_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cefr_evidence')),
    sa.UniqueConstraint('sense_id', 'source_id', name='uq_cefr_per_source')
    )
    op.create_index('ix_cefr_evidence_sense', 'cefr_evidence', ['sense_id'], unique=False)
    op.create_table('frequency_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('frequency_per_million', sa.Float(), nullable=True),
    sa.Column('raw_value', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_frequency_evidence_sense_id_vocabulary_senses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['vocabulary_sources.id'], name=op.f('fk_frequency_evidence_source_id_vocabulary_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frequency_evidence')),
    sa.UniqueConstraint('sense_id', 'source_id', name='uq_freq_per_source')
    )
    op.create_index('ix_freq_evidence_sense', 'frequency_evidence', ['sense_id'], unique=False)
    op.create_table('sense_categories',
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('assigned_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_sense_categories_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_sense_categories_sense_id_vocabulary_senses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sense_id', 'category_id', name=op.f('pk_sense_categories'))
    )
    op.create_table('sense_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_sense_definitions_sense_id_vocabulary_senses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sense_definitions'))
    )
    op.create_index('ix_definitions_sense', 'sense_definitions', ['sense_id'], unique=False)
    op.create_table('sense_examples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('example', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_sense_examples_sense_id_vocabulary_senses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sense_examples'))
    )
    op.create_index('ix_examples_sense', 'sense_examples', ['sense_id'], unique=False)
    op.create_table('sense_priorities',
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('components', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_sense_priorities_sense_id_vocabulary_senses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sense_id', name=op.f('pk_sense_priorities'))
    )
    op.create_table('sense_source_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.String(length=400), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_sense_source_records_sense_id_vocabulary_senses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['vocabulary_sources.id'], name=op.f('fk_sense_source_records_source_id_vocabulary_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sense_source_records')),
    sa.UniqueConstraint('source_id', 'source_record_id', name='uq_source_record_once')
    )
    op.create_index('ix_sense_sources_sense', 'sense_source_records', ['sense_id'], unique=False)
    op.create_table('sense_translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('translation', sa.String(length=400), nullable=False),
    sa.Column('translation_normalized', sa.String(length=400), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_sense_translations_sense_id_vocabulary_senses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sense_translations'))
    )
    op.create_index('ix_translations_norm', 'sense_translations', ['translation_normalized'], unique=False)
    op.create_index('ix_translations_sense', 'sense_translations', ['sense_id'], unique=False)
    op.create_table('sense_wordnet_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('synset_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_sense_wordnet_links_sense_id_vocabulary_senses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['synset_id'], ['wordnet_synsets.id'], name=op.f('fk_sense_wordnet_links_synset_id_wordnet_synsets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sense_wordnet_links')),
    sa.UniqueConstraint('sense_id', 'synset_id', name='uq_sense_synset')
    )
    op.create_index('ix_sense_wordnet_sense', 'sense_wordnet_links', ['sense_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', name='student_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_students_teacher_id_teachers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    op.create_index('ix_students_teacher_status', 'students', ['teacher_id', 'status'], unique=False)
    op.create_table('teacher_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_teacher_sessions_teacher_id_teachers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_teacher_sessions_token_hash'))
    )
    op.create_table('vocabulary_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('flag', sa.Enum('RARE', 'ARCHAIC', 'OBSOLETE', 'TECHNICAL', 'SPECIALIZED', 'PROPER_NAME', 'OFFENSIVE', 'AMERICAN', 'BRITISH', name='sense_flag', native_enum=False), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_vocabulary_flags_sense_id_vocabulary_senses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['vocabulary_sources.id'], name=op.f('fk_vocabulary_flags_source_id_vocabulary_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_flags')),
    sa.UniqueConstraint('sense_id', 'flag', name='uq_flag_per_sense')
    )
    op.create_index('ix_flags_sense', 'vocabulary_flags', ['sense_id'], unique=False)
    op.create_table('vocabulary_forms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('form', sa.String(length=200), nullable=False),
    sa.Column('form_normalized', sa.String(length=200), nullable=False),
    sa.Column('is_lemma', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_vocabulary_forms_sense_id_vocabulary_senses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_forms')),
    sa.UniqueConstraint('sense_id', 'form_normalized', name='uq_form_per_sense')
    )
    op.create_index('ix_forms_norm', 'vocabulary_forms', ['form_normalized'], unique=False)
    op.create_table('vocabulary_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_vocabulary_sets_teacher_id_teachers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_sets')),
    sa.UniqueConstraint('teacher_id', 'name', name='uq_set_name_per_teacher')
    )
    op.create_table('wordnet_relations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_synset_id', sa.Uuid(), nullable=False),
    sa.Column('to_synset_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['from_synset_id'], ['wordnet_synsets.id'], name=op.f('fk_wordnet_relations_from_synset_id_wordnet_synsets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_synset_id'], ['wordnet_synsets.id'], name=op.f('fk_wordnet_relations_to_synset_id_wordnet_synsets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wordnet_relations')),
    sa.UniqueConstraint('from_synset_id', 'to_synset_id', 'relation', name='uq_wordnet_relation')
    )
    op.create_index('ix_wordnet_rel_from', 'wordnet_relations', ['from_synset_id'], unique=False)
    op.create_table('student_vocabulary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('learning_state', sa.Enum('NEW', 'ASSIGNED', 'ENCOUNTERED', 'LEARNING', 'REVIEWING', 'MASTERED', name='learning_state', native_enum=False), nullable=False),
    sa.Column('teacher_priority_override', sa.String(length=20), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_student_vocabulary_sense_id_vocabulary_senses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_vocabulary_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_vocabulary')),
    sa.UniqueConstraint('student_id', 'sense_id', name='uq_student_sense')
    )
    op.create_index('ix_student_vocab_sense', 'student_vocabulary', ['sense_id'], unique=False)
    op.create_index('ix_student_vocab_student_state', 'student_vocabulary', ['student_id', 'learning_state'], unique=False)
    op.create_table('teacher_priority_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('priority_level', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_teacher_priority_overrides_sense_id_vocabulary_senses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_teacher_priority_overrides_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_priority_overrides')),
    sa.UniqueConstraint('student_id', 'sense_id', name='uq_override_per_student_sense')
    )
    op.create_index('ix_overrides_student', 'teacher_priority_overrides', ['student_id'], unique=False)
    op.create_table('vocabulary_set_items',
    sa.Column('set_id', sa.Uuid(), nullable=False),
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_vocabulary_set_items_sense_id_vocabulary_senses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['vocabulary_sets.id'], name=op.f('fk_vocabulary_set_items_set_id_vocabulary_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('set_id', 'sense_id', name=op.f('pk_vocabulary_set_items'))
    )
    op.create_index('ix_set_items_sense', 'vocabulary_set_items', ['sense_id'], unique=False)
    op.create_table('review_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_vocabulary_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('sense_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rating', sa.Enum('HARD', 'MEDIUM', 'EASY', name='teacher_rating', native_enum=False), nullable=False),
    sa.Column('fsrs_grade', sa.Enum('AGAIN', 'HARD', 'GOOD', 'EASY', name='fsrs_grade', native_enum=False), nullable=False),
    sa.Column('previous_state_json', sa.Text(), nullable=True),
    sa.Column('new_state_json', sa.Text(), nullable=True),
    sa.Column('previous_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_review_events_sense_id_vocabulary_senses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_review_events_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_vocabulary_id'], ['student_vocabulary.id'], name=op.f('fk_review_events_student_vocabulary_id_student_vocabulary'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_review_events_teacher_id_teachers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_events'))
    )
    op.create_index('ix_review_events_student_time', 'review_events', ['student_id', 'reviewed_at'], unique=False)
    op.create_index('ix_review_events_sv_time', 'review_events', ['student_vocabulary_id', 'reviewed_at'], unique=False)
    op.create_table('student_fsrs_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_vocabulary_id', sa.Uuid(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fsrs_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['student_vocabulary_id'], ['student_vocabulary.id'], name=op.f('fk_student_fsrs_states_student_vocabulary_id_student_vocabulary'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_fsrs_states')),
    sa.UniqueConstraint('student_vocabulary_id', name=op.f('uq_student_fsrs_states_student_vocabulary_id'))
    )
    op.create_index('ix_fsrs_due_at', 'student_fsrs_states', ['due_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fsrs_due_at', table_name='student_fsrs_states')
    op.drop_table('student_fsrs_states')
    op.drop_index('ix_review_events_sv_time', table_name='review_events')
    op.drop_index('ix_review_events_student_time', table_name='review_events')
    op.drop_table('review_events')
    op.drop_index('ix_set_items_sense', table_name='vocabulary_set_items')
    op.drop_table('vocabulary_set_items')
    op.drop_index('ix_overrides_student', table_name='teacher_priority_overrides')
    op.drop_table('teacher_priority_overrides')
    op.drop_index('ix_student_vocab_student_state', table_name='student_vocabulary')
    op.drop_index('ix_student_vocab_sense', table_name='student_vocabulary')
    op.drop_table('student_vocabulary')
    op.drop_index('ix_wordnet_rel_from', table_name='wordnet_relations')
    op.drop_table('wordnet_relations')
    op.drop_table('vocabulary_sets')
    op.drop_index('ix_forms_norm', table_name='vocabulary_forms')
    op.drop_table('vocabulary_forms')
    op.drop_index('ix_flags_sense', table_name='vocabulary_flags')
    op.drop_table('vocabulary_flags')
    op.drop_table('teacher_sessions')
    op.drop_index('ix_students_teacher_status', table_name='students')
    op.drop_table('students')
    op.drop_index('ix_sense_wordnet_sense', table_name='sense_wordnet_links')
    op.drop_table('sense_wordnet_links')
    op.drop_index('ix_translations_sense', table_name='sense_translations')
    op.drop_index('ix_translations_norm', table_name='sense_translations')
    op.drop_table('sense_translations')
    op.drop_index('ix_sense_sources_sense', table_name='sense_source_records')
    op.drop_table('sense_source_records')
    op.drop_table('sense_priorities')
    op.drop_index('ix_examples_sense', table_name='sense_examples')
    op.drop_table('sense_examples')
    op.drop_index('ix_definitions_sense', table_name='sense_definitions')
    op.drop_table('sense_definitions')
    op.drop_table('sense_categories')
    op.drop_index('ix_freq_evidence_sense', table_name='frequency_evidence')
    op.drop_table('frequency_evidence')
    op.drop_index('ix_cefr_evidence_sense', table_name='cefr_evidence')
    op.drop_table('cefr_evidence')
    op.drop_table('wordnet_synsets')
    op.drop_table('vocabulary_sources')
    op.drop_index('ix_senses_priority', table_name='vocabulary_senses')
    op.drop_index('ix_senses_pos', table_name='vocabulary_senses')
    op.drop_index('ix_senses_headword_norm', table_name='vocabulary_senses')
    op.drop_index('ix_senses_cefr', table_name='vocabulary_senses')
    op.drop_table('vocabulary_senses')
    op.drop_table('teachers')
    op.drop_table('categories')
    # ### end Alembic commands ###
